version: '3.8'

services:
  postgres:
    image: postgres:17.5-bookworm
    container_name: wolfconnect-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wolfconnect
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  wolfconnect:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wolfconnect-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./config:/opt/wolfconnect/config

volumes:
  postgres-data:
