build:
  maxIssues: 0

style:
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2']
    ignoreHashCodeFunction: true


formatting:
  active: true
  autoCorrect: false

naming:
  FunctionNaming:
    functionPattern: '^[a-z][a-zA-Z0-9]*$'
